# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: daniel <daniel@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/02/06 20:21:48 by daniel            #+#    #+#              #
#    Updated: 2025/02/06 20:26:16 by daniel           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@c++ *cpp -std=c++98 -Wall -Wextra -Werror -o scavtrap
	@./scavtrap

re: 
	all fclean

fclean:
	rm -f scavtrap