# Usa la imagen base oficial de WordPress
FROM wordpress:6.0

# Configura las variables de entorno necesarias para WordPress
ENV WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
ENV WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
ENV WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
ENV WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

# Exponer el puerto 80 para WordPress
EXPOSE 80