
# Dockerfile para WordPress
FROM wordpress:6.0

# Configura las variables de entorno necesarias para WordPress
ENV WORDPRESS_DB_HOST=mariadb
ENV WORDPRESS_DB_NAME=wordpress_db
ENV WORDPRESS_DB_USER=wordpress_user
ENV WORDPRESS_DB_PASSWORD=wordpress_password

# Exponer el puerto 80 para WordPress
EXPOSE 80