# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: druiz-ca <druiz-ca@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/02/02 11:29:56 by druiz-ca          #+#    #+#              #
#    Updated: 2025/02/02 14:08:54 by druiz-ca         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@c++ *.cpp -Wall -Werror -Wextra -std=c++98 -o fixed
	@echo "Fixed compiled"
	@./fixed

re:
	fclean all

fclean:
	rm -f fixed