# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: daniel <daniel@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/21 18:12:15 by daniel            #+#    #+#              #
#    Updated: 2025/01/21 19:35:50 by daniel           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@c++ *.cpp -Wall -Werror -Wextra -std=c++98 -o brain
	@echo "Compiling and running brain \n"
	@./brain

fclean:
	@rm -f brain

# el @ es solo para que no imprima el comando en la terminal