# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: druiz-ca <druiz-ca@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/21 18:12:15 by daniel            #+#    #+#              #
#    Updated: 2025/02/15 14:12:16 by druiz-ca         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@c++ *.cpp -Wall -Werror -Wextra -std=c++98 -o brain
	@echo "Compiling and running brain \n"
	@./brain

fclean:
	@rm -f brain